kbuild: split x*alloc() functions in kconfig to scripts/include/xalloc.h
These functions will be useful for other host programs.

Change-Id: Ib65562893503402fbaafc5bb3dd14d2bc1df2137
Signed-off-by: Masahiro Yamada <masahiroy@kernel.org>
Git-commit: a9d83d74783b00f9189c14180f77bbed133b092c
Git-repo: git://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git
[quic_satyap@quicinc.com:
 discarded changes to below files which aren't present in soc repo:
 error: scripts/kconfig/confdata.c: does not exist in index
 error: scripts/kconfig/expr.c: does not exist in index
 error: scripts/kconfig/lkc.h: does not exist in index
 error: scripts/kconfig/menu.c: does not exist in index
 error: scripts/kconfig/preprocess.c: does not exist in index
 error: scripts/kconfig/symbol.c: does not exist in index
 error: scripts/kconfig/util.c: does not exist in index]
Signed-off-by: Satya Durga Srinivasu Prabhala <quic_satyap@quicinc.com>