kconfig: remove P_SYMBOL property
P_SYMBOL is a pseudo property that was previously used for data linking
purposes.

It is no longer used except for debug prints. Remove it.

Change-Id: Ib9ccf66f834c62ff8603befa47fc172ff278d31c
Signed-off-by: Masahiro Yamada <masahiroy@kernel.org>
Git-commit: 96490176f1e11947be2bdd2700075275e2c27310
Git-repo: git://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git
[quic_satyap@quicinc.com:
 discarded changes to below files which aren't present in soc repo:
 error: scripts/kconfig/expr.h: does not exist in index
 error: scripts/kconfig/symbol.c: does not exist in index]
Signed-off-by: Satya Durga Srinivasu Prabhala <quic_satyap@quicinc.com>